docs/src/deploy/dynamic_routing.md
docs/src/operation/cluster.md
docs/translations/cn/deploy/dynamic_routing.md
docs/translations/cn/operation/cluster.md

Add docs for CeresDB cluster mode.

docs: update cluster mode docs

---

.gitignore
docs/src/en/sdk/python.md

Add the English docs for python sdk usage.

feat: python sdk doc (En)

---

docs/src/cn/sdk/go.md
docs/src/en/sdk/go.md

doc: add add golang sdk doc

---

docs/book.toml
docs/sidebar.js
docs/style.css
docs/theme/index.hbs

Add toc of page.
Refer to https://github.com/JorelAli/mdBook-pagetoc.

feat: add toc of page

---

docs/src/en/SUMMARY.md

bug: make link available

---

docs/src/cn/operation/block_list.md
docs/src/en/operation/block_list.md

This is a followup PR for <https://github.com/CeresDB/ceresdb/pull/659>

chore: update links

---

docs/src/en/cluster_deployment/with_meta.md

fix: fix config file name

---

docs/src/cn/cluster_deployment/with_meta.md
docs/src/en/cluster_deployment/with_meta.md

Add note for with meta deploy doc.

fix: add with meta deploy note

---

docs/src/cn/SUMMARY.md
docs/src/cn/design/storage.md
docs/src/cn/sdk/python.md
docs/src/en/SUMMARY.md
docs/src/en/design/storage.md
docs/src/en/sdk/python.md

- Update the usage of python sdk for some changes in its apis.
- Rename `clustering` to `cluster` in the docs.

chore: update usage of latest python sdk

---

docs/src/cn/cluster_deployment/no_meta.md
docs/src/en/cluster_deployment/no_meta.md

Fix image version in no meta deploy docs.

fix: fix no meta image version

---

docs/src/cn/sdk/java.md
docs/src/en/sdk/java.md

doc: update java sdk to 1.0.1

---

docs/src/cn/quick_start.md
docs/src/en/quick_start.md

fix: error links

---

docs/src/en/dev/style_guide.md

Close <https://github.com/CeresDB/ceresdb/issues/138>

feat: update error handle

---

docs/src/cn/cluster_deployment/with_meta.md
docs/src/en/cluster_deployment/with_meta.md
docs/src/resources/config_kafka_oss.toml
docs/src/resources/config_local_oss.toml
docs/src/resources/config_obkv_oss.toml

fix:disable disk cache

---

docs/src/resources/grafana-dashboard.json

Dashboard for 1.2 ceresdb-server

Update grafana dashboard

---

docs/src/cn/cluster_deployment/with_meta.md
docs/src/en/cluster_deployment/with_meta.md

Fix startup script for CeresMeta cluster.

fix: fix ceresmta cluster start script

---

docs/src/cn/sdk/go.md
docs/src/cn/sdk/python.md
docs/src/cn/sdk/rust.md
docs/src/en/sdk/go.md
docs/src/en/sdk/python.md
docs/src/en/sdk/rust.md

Add version releated links for each client

docs: add client release link

---

docs/src/cn/operation/ceresmeta.md
docs/src/en/operation/ceresmeta.md

feat: support update flow limiter

---

docs/src/cn/ecosystem/influxdb.md
docs/src/en/ecosystem/influxdb.md
docs/src/en/sdk/rust.md

add influxdb notes

---

docs/src/cn/sql/ddl/create_table.md
docs/src/en/sql/ddl/create_table.md

Related with https://github.com/CeresDB/ceresdb/issues/1017

add sql comment

---

docs/src/cn/operation/ceresmeta.md
docs/src/en/operation/ceresmeta.md

Add new cluster operation for `CeresMeta`.

docs: add new cluster operation for ceresmeta

---

docs/src/cn/sql/ddl/create_table.md
docs/src/en/sql/ddl/create_table.md

Dictionary is supported in 1.2.5 release.

docs: add dictionary tag column

---

docs/src/cn/SUMMARY.md
docs/src/en/SUMMARY.md

chore: update summary

---

docs/src/cn/operation/ceresmeta.md
docs/src/en/operation/ceresmeta.md

feat: add deploy mode api

---

.asf.yaml

config: add `.asf.yaml`

---

.asf.yaml

mirror of https://github.com/apache/incubator-horaedb/pull/1385

docs: sync GH activities to commits only

---

docs/theme/index.hbs

Current i18n path is wrong, and this PR will fix it in a workaround way.

fix: wrong i18n path

---

.github/workflows/deploy.yml

related https://github.com/apache/incubator-horaedb-docs/pull/119

fix: deploy typo

---

content/cn/_index.md
content/en/_index.md

Ref: https://www.apachecon.com/event-images/

add banner for na2024

---

content/cn/docs/user-guide/cluster_deployment/_index.md
content/cn/docs/user-guide/cluster_deployment/with_meta.md
content/en/docs/user-guide/cluster_deployment/_index.md
content/en/docs/user-guide/cluster_deployment/with_meta.md

fix: correct 404 links

---

layouts/partials/footer.html

add create issue link in footer
